### ISSUE TITLE
technical question

### ISSUE THREAD

**Issue by TigerClaw33** [aenniw/ARDUINO#64]
Hi, 

I have some questions.

- You use a H-bridge with DC 43A max. And the DC motor needs a max. of 20A. But you use a 4-5A fuse. I don't think that it will has a max. torque of 8 Nm, but in case of heavy weight it will need a higher current isn't it ?
- do you think a stepper with hight torque would also work? I think 2-4 Nm would be enough and in this case I would need a motor driver instead of h bridge or relay. 

Nice idea. I have some printers and it makes fun to mod the table with a engine :)

**Comment by iLLiac4** [comment]
1. To recommend the working fuse I have tested with current clamp the power and have seen that the motor has never exceeded 6A when in normal working condition. Since those fuse that we have used are AC fuses and not DC one the current must be a little higher than with the dc one (dc fuses are spiral and acts as spring).  So I have tested and saw that 4-5A fuse is ok to be used to protect the motor with 6A usage. if the motor is stucked and too much current flows it will burn the fuse to protect the motor. So if a motor is rated with 20A it does not mean that it will use 20A to be able to lift the table.  If you measure that the motor will need 6A you will need to replace the fuse with stronger one 10A for example. Also from my experience the H-Bridge is less strong than relay one. The relay one causes more stress to the mechanism but from my experience it is more fluent (i do not know why).

2. Stepper motor will work but will need a code change and it will be much more expensive. Also the motor driver will need to be much stronger and I doubt that the one for 3d printers will be ok since the strongest can handle current up to 5A i think. aenniw has used those motors because they are cheap, strong and small. The downside is that they are not stepped controlled one so there is still a problem that rotary encoder losses the steps end it slowly decalibrate itself. He has tried to find a solution but he will tell you more if he finds time. Also they are not as quite asa commercial one.

But I have two tables one is 120cm and the other 160cm. On the tallest one I have two monitors with metal stands and a small form factor computer and it lifts the table. As a power supply I use small old atx power supply from and old dell computer from junkyard.
